### ISSUE TITLE
Radio La Serena

### ISSUE THREAD

**Issue by ffuentese** [Alplox/tele#2]
Podrías agregar la radio de La Serena?  Fue bien importante durante las protestas y tienen señal en youtube, también en Facebook.

En este momento emiten en vivo en [este link](https://www.youtube.com/watch?v=tWFAqALLE90)
 y el canal es [este](https://www.youtube.com/channel/UClJiriqxFwmmVIQeASJfICQ)

**Comment by Alplox** [comment]
emiten siempre simultaneamente por youtube o es solo por ahora? (para quizas luego agregar radios que no transmitan video igual)
