### ISSUE TITLE
duda

### ISSUE THREAD

**Issue by Felipe21** [Alplox/tele#6]
Hola, disculpen tendran algun script apra poder saar links automaticos de paginas que impartan canales de tv como www.supertelevisionhd.net o cablegratis.tv? son canales que se van actualizando, entonces algo asi como indexar un enlace en el script para que vara revisando cada tanto que cambie y su cambio sea automatico.
ps: buen proyecto quede loco

**Comment by Alplox** [comment]
No, no tengo/existe tal script, todos los enlaces en el proyecto se añaden de forma manual.

La idea es valida pero choca con dos cosas 
1-escapa a mis habilidades como desarrollador xd
2-estos sitios suelen morir tras unos meses (casi siempre debido a que retransmiten canales de suscripción, el clásico tnt sport)
